import json
import re
from pathlib import Path

data_dir = Path("c:/Mioshie_Sites/guia_johrei/data")

# Load audit data (generated by scripts/generate_orphan_audit.py)
audit = json.load(open(data_dir / "_audit_articles_pergunta_sem_resposta.json", encoding="utf-8"))
# Current format uses a flat "orphans" list (not the old "truly_orphan.items" structure)
orphan_items = audit.get("orphans", audit.get("truly_orphan", {}).get("items", []))
orphan_ids = {item["id"]: item["source_file"] for item in orphan_items if item.get("id")}

print(f"Total truly orphan: {len(orphan_ids)}")

# Group by source file
files_needed = {}
for iid, sf in orphan_ids.items():
    files_needed.setdefault(sf, []).append(iid)

# Analyze each orphan article
all_patterns = {}
multi_turn_candidates = []

for sf, ids in files_needed.items():
    data = json.load(open(data_dir / sf, encoding="utf-8"))
    for item in data:
        if item.get("id") not in ids:
            continue
        content = item.get("content_pt", "")
        lines = [l.strip() for l in content.split("\n") if l.strip()]

        # Count Pergunta markers
        n_pergunta = sum(1 for l in lines if re.search(r"Pergunta\s+do\s+(Fiel|Ministrante)", l, re.I))
        
        # Look for answer markers without the standard format
        answer_lines = []
        for l in lines:
            if re.search(r"Ensinamento\s+de\s+Meishu|Instru[çc][aã]o\s+de|Resposta\s+de|Meishu-Sama\s*[:\"]", l, re.I):
                answer_lines.append(l[:80])

        # Check for standalone Meishu-Sama header (without "Resposta de" or "Orientação de")
        meishu_headers = [l for l in lines if re.match(r"^Meishu-Sama\s*$", l, re.I)]
        ensinamento_headers = [l for l in lines if re.search(r"Ensinamento\s+de\s+Meishu", l, re.I)]
        
        pattern = {
            "id": item["id"],
            "title": item.get("title_pt", "")[:60],
            "n_pergunta": n_pergunta,
            "answer_lines": answer_lines[:3],
            "meishu_headers": meishu_headers,
            "ensinamento_headers": ensinamento_headers[:2],
            "content_start": content[:200].replace("\n", " | "),
        }
        all_patterns[item["id"]] = pattern

        if n_pergunta > 1:
            multi_turn_candidates.append(item["id"])

# Show summary
print("\n=== ANSWER MARKER PATTERNS ===")
for iid, p in list(all_patterns.items())[:15]:
    print(f"\n[{iid}] {p['title']}")
    print(f"  Perguntas: {p['n_pergunta']}")
    if p["answer_lines"]:
        print(f"  Answer markers: {p['answer_lines']}")
    if p["meishu_headers"]:
        print(f"  'Meishu-Sama' header: {p['meishu_headers']}")
    if p["ensinamento_headers"]:
        print(f"  'Ensinamento de' header: {p['ensinamento_headers']}")
    print(f"  Start: {p['content_start'][:150]}")

print(f"\n=== MULTI-TURN CANDIDATES ({len(multi_turn_candidates)}) ===")
for iid in multi_turn_candidates:
    p = all_patterns[iid]
    print(f"  [{iid}] {p['title']} — {p['n_pergunta']} perguntas")
